export const addUser = (data) => {
  const { firstName, lastName, login, auditRatio } = data;
  console.log(firstName, lastName, login);
  const user = document.createElement('div');
  user.classList.add('user');
  const first = document.createElement('p');
  first.classList.add('username');
  first.textContent = `You firstname is ${firstName}`;
  const last = document.createElement('p');
  last.classList.add('username');
  last.textContent = `You lastname is ${lastName}`;
  const log = document.createElement('p');
  log.classList.add('username');
  log.textContent = `You login is ${login}`;
  const audit = document.createElement('p');
  audit.classList.add('username');
  audit.textContent = `You audit rating is ${Math.round(auditRatio * 10) / 10}`;
  user.append(first, last, log, audit);
  body.textContent = '';
  body.append(user);
};
