export const addUser = (data, body) => {
  const { firstName, lastName, login, attrs } = data;
  console.log(firstName, lastName, login, attrs.image);
  const user = document.createElement('div');
  user.classList.add('user');
  const name = document.createElement('p');
  name.classList.add('username');
  name.textContent = `Welcome ${firstName} ${lastName}`;
  const log = document.createElement('p');
  log.classList.add('username');
  log.textContent = `Nickname: ${login}`;
  const mail = document.createElement('p');
  mail.classList.add('username');
  mail.textContent = `Friends can write you to ${attrs.email}`;
  const img = new Image();
  img.classList.add('avatar');
  img.src = `${attrs.image}`;
  const logoutBtn = document.createElement('button');
  logoutBtn.classList.add('logout');
  logoutBtn.textContent = 'Log out';
  user.append(name, log, mail, img, logoutBtn);
  body.textContent = '';
  body.append(user);
};
